version: "3.9"
services:
    app:
        container_name: challenge-prexcard-app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
            - /var/www/vendor
        ports:
            - "8080:80"
        networks:
            - laravel
        command: >
            sh -c "composer install && php-fpm"

    webserver:
        image: nginx:latest
        depends_on:
            - app
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8081:80"
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: localhost
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: Pass.123
            command: --wait-timeout=28800 --interactive-timeout=28800
        ports:
            - "3307:3306"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
